# Generated by Django 5.0.6 on 2024-05-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
    ]
