# Generated by Django 5.0.6 on 2024-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_comment_id_comments_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
